apiVersion: v1
kind: Namespace
metadata:
  name:  http-echo
---
apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  namespace: http-echo
  labels:
    app: http-echo
spec:
  containers:
  - name: http-echo
    image: hashicorp/http-echo
    args:
      - '-text=Hello World'    
    resources:
      limits:
        memory: "128Mi"
    ports:
      - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: http-echo
spec:
  type: LoadBalancer
  selector:
    app: http-echo
  ports:
  - port: 5678
    targetPort: 5678
