apiVersion: v1
kind: Namespace
metadata:
  name:  http-echo
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: http-echo
spec:
  type: ClusterIP
  selector:
    app: http-echo-deployment
  ports:
  - port: 5678
    targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: http-echo
  name: http-echo-deployment
  labels:
    app: http-echo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
        - '-text=Hello, World!'
        ports:
        - containerPort: 5678